import random
from turtle import Turtle, done


def race(turtles, turns=5):
    for turn in range(turns):
        for idx, turtle in enumerate(turtles):
            angle = choose_angle_to_turn()
            distance = choose_distance_to_walk()

            msg = 'Turtle ' + idx + ' chooses to turn ' + angle + ' degrees and takes ' + distance + ' steps forward.'
            print(msg)
            turtle.right(angle)
            turtle.forward(distance)


def choose_angle_to_turn():
    angles = [0, 60, 120, 180, 240, 300]
    # the above could be generated by `angles = range(0, 360, 60)` too
    angle_to_turn = random.choice(angles)
    return angle_to_turn


def choose_distance_to_walk():
    distances = range(0, 50, 5)
    # the above creates values like:
    # `distances = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]`
    distance_to_walk = random.choice(distances)
    return distance_to_walk


def main():
    mary = Turtle()
    susan = Turtle(shape='arrow')
    billy = Turtle(shape='turtle')

    turtles_in_race = [mary, susan, billy]
    race(turtles_in_race, turns=20)
    done()


if __name__ == '__main__':
    main()
